'use client';
import { useState } from 'react';
import { deleteProject, setProjectStatus, signOut } from '../../app/admin/actions';
import { ProjectEditor } from './project-editor';
import { ArrowUpRight, LogOut, Plus, Trash2 } from 'lucide-react';

export function Dashboard({ projects }) {
  const [editor, setEditor] = useState(null);
  return <main className="wrap min-h-screen py-10 md:py-16">
    <header className="flex flex-wrap items-center justify-between gap-5 border-b border-[var(--line)] pb-8"><div><p className="mono text-[10px] uppercase tracking-[.2em] text-[var(--accent)]">Private workspace</p><h1 className="serif mt-2 text-5xl tracking-[-.06em]">Projects</h1><p className="mt-2 text-xs text-[var(--muted)]">Manage drafts and published work.</p></div><div className="flex gap-3"><a href="/" className="button-outline px-4 py-3 text-xs">View site <ArrowUpRight className="ml-2 inline" size={13}/></a><button onClick={()=>setEditor({new:true})} className="button-primary px-4 py-3 text-xs font-semibold"><Plus className="mr-1 inline" size={14}/> New project</button><form action={signOut}><button className="button-outline px-3 py-3" aria-label="Sign out"><LogOut size={15}/></button></form></div></header>
    <div className="mt-8 space-y-3">{projects.map((project)=><article key={project.id} className="grid items-center gap-5 border border-[var(--line)] bg-white/50 p-5 md:grid-cols-[1fr_auto]"><div className="flex items-center gap-4"><div className="hidden h-[68px] w-24 shrink-0 overflow-hidden bg-[#e7e9e2] sm:block">{project.image_url && <img src={project.image_url} alt="" className="h-full w-full object-cover"/>}</div><div><div className="flex flex-wrap items-center gap-3"><h2 className="serif text-2xl tracking-[-.04em]">{project.title}</h2><span className={'rounded-full px-2.5 py-1 text-[9px] uppercase tracking-wider '+(project.status==='published'?'bg-[#e4eee3] text-[#527950]':'bg-[#f3ead8] text-[#97703a]')}>{project.status}</span></div><p className="mt-1 text-xs text-[var(--muted)]">{project.tagline}</p><p className="mt-2 text-[10px] text-[var(--muted)]">{project.tech_stack?.join(' · ')}</p></div></div><div className="flex flex-wrap items-center gap-2"><button onClick={()=>setEditor(project)} className="button-outline px-3 py-2 text-[11px]">Edit</button><form action={setProjectStatus}><input type="hidden" name="id" value={project.id}/><input type="hidden" name="status" value={project.status==='published'?'draft':'published'}/><button className="button-primary px-3 py-2 text-[11px]">{project.status==='published'?'Unpublish':'Publish to public'}</button></form><form action={deleteProject}><input type="hidden" name="id" value={project.id}/><button className="button-outline grid h-[34px] w-[34px] place-items-center" aria-label={'Delete '+project.title}><Trash2 size={14}/></button></form></div></article>)}</div>
    {projects.length===0 && <div className="mt-8 border border-dashed border-[var(--line)] py-20 text-center"><p className="serif text-3xl">A little room to begin.</p><p className="mt-2 text-xs text-[var(--muted)]">Create your first project to get started.</p></div>}
    {editor && <ProjectEditor project={editor.new ? null : editor} onClose={()=>setEditor(null)}/>}
  </main>;
}
